# -*- coding: utf-8 -*-
"""Double pendulum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9FB4gFauh9kbr2gVdWcH-FbxaC_hAyR
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

def solve_double_pendulum(initial_conditions, t_max, omega0=np.sqrt(9.81)):
    """
    Solves the double pendulum equations of motion provided.

    Equations:
    2*dd_phi1 + dd_phi2*cos(phi1-phi2) + (d_phi2)^2*sin(phi1-phi2) + 2*omega0^2*sin(phi1) = 0
    dd_phi2 + dd_phi1*cos(phi1-phi2) - (d_phi1)^2*sin(phi1-phi2) + omega0^2*sin(phi2) = 0

    Args:
        initial_conditions: list/array [phi1, d_phi1, phi2, d_phi2] (angles in rads, velocities in rad/s)
        t_max: maximum time for simulation (t_min is assumed 0)
        omega0: natural frequency of the pendulum (sqrt(g/L))

    Returns:
        t: array of time points
        solution: array of shape (len(t), 4) with columns [phi1, d_phi1, phi2, d_phi2]
    """

    # Create time array with dt < 0.05
    dt = 0.049  # Slightly less than 0.05 to be safe
    num_points = int(np.ceil(t_max / dt)) + 1
    t = np.linspace(0, t_max, num_points)

    def deriv(y, t, omega0):
        phi1, z1, phi2, z2 = y # z1 is d_phi1, z2 is d_phi2
        delta = phi1 - phi2
        omega0_sq = omega0**2

        # We need to solve for alpha1 (dd_phi1) and alpha2 (dd_phi2)
        # The system can be written as matrix equation M * [alpha1, alpha2]^T = B
        # M = [[2, cos(delta)], [cos(delta), 1]]
        # B = [ -z2^2*sin(delta) - 2*omega0^2*sin(phi1),
        #        z1^2*sin(delta) - omega0^2*sin(phi2) ]

        # Calculate the RHS terms (vector B)
        b1 = -z2**2 * np.sin(delta) - 2 * omega0_sq * np.sin(phi1)
        b2 = z1**2 * np.sin(delta) - omega0_sq * np.sin(phi2)

        # Solve the linear system using Cramer's rule for explicit formulas
        # Determinant of M = 2*1 - cos(delta)*cos(delta)
        det_M = 2 - np.cos(delta)**2

        # alpha1 = (b1*1 - b2*cos(delta)) / det
        alpha1 = (b1 - b2 * np.cos(delta)) / det_M

        # alpha2 = (2*b2 - b1*cos(delta)) / det
        alpha2 = (2 * b2 - b1 * np.cos(delta)) / det_M

        return [z1, alpha1, z2, alpha2]

    # Solve ODE
    solution = odeint(deriv, initial_conditions, t, args=(omega0,))
    return t, solution

# define a function to plot the results

def plot_results(t, solution, omega0):
    # Extract state variables
    phi1 = solution[:, 0]
    d_phi1 = solution[:, 1]
    phi2 = solution[:, 2]
    d_phi2 = solution[:, 3]

    # Create figure with 3 subplots
    fig, axs = plt.subplots(1, 3, figsize=(18, 5))

    # 1. Time Series Plot
    axs[0].plot(t, phi1, label=r'$\phi_1$ (Upper)')
    axs[0].plot(t, phi2, label=r'$\phi_2$ (Lower)', alpha=0.8)
    axs[0].set_title(rf'Motion ($\omega_0$={omega0:.2f} rad/s)')
    axs[0].set_xlabel('Time (s)')
    axs[0].set_ylabel('Angle (radians)')
    axs[0].legend()
    axs[0].grid(True)

    # 2. Phase Space Plot (Pendulum 1)
    axs[1].plot(phi1, d_phi1, color='tab:blue')
    axs[1].set_title(r'Phase Space: Upper Pendulum ($\phi_1$)')
    axs[1].set_xlabel(r'Angle $\phi_1$ (rad)')
    axs[1].set_ylabel(r'Velocity $\dot{\phi}_1$ (rad/s)')
    axs[1].grid(True)

    # 3. Phase Space Plot (Pendulum 2)
    axs[2].plot(phi2, d_phi2, color='tab:orange')
    axs[2].set_title(r'Phase Space: Lower Pendulum ($\phi_2$)')
    axs[2].set_xlabel(r'Angle $\phi_2$ (rad)')
    axs[2].set_ylabel(r'Velocity $\dot{\phi}_2$ (rad/s)')
    axs[2].grid(True)

    plt.tight_layout()
    plt.show()

# Example Usage

# Simulation parameters
t_max = 20  # Simulate for 20 seconds

# Initial conditions: [phi1, d_phi1, phi2, d_phi2]
# Starting with both pendulums at 90 degrees (horizontal) and at rest
y0 = [np.pi/2, 0, np.pi/2, 0]

# Solve
# Let's say L=1.0 and g=9.81, so omega0 = sqrt(9.81/1.0) approx 3.13
omega0 = 3.13
t, solution = solve_double_pendulum(y0, t_max, omega0)

#Plot the results
# Call the plotting function
plot_results(t, solution, omega0)

"""# Task
Define a function `plot_poincare_section(solution)` to generate a Poincaré section for the double pendulum. This function should identify indices where `phi1` crosses zero with positive velocity (`d_phi1 > 0`), interpolate the corresponding `phi2` and `d_phi2` values at these exact crossing times, map `phi2` to the interval `[-pi, pi]`, and display a scatter plot of `phi2` vs `d_phi2`.

After defining the function, update the simulation parameters to set `t_max = 100` seconds, solve the system again with the existing initial conditions, and call `plot_poincare_section` to visualize the result.

## Define Poincaré Plot Function

### Subtask:
Create a function `plot_poincare_section` to generate a Poincaré section plot.

**Reasoning**:
Define the `plot_poincare_section` function as per the instructions to visualize the Poincaré section of the double pendulum.
"""

def plot_poincare_section(t, solution):
    """
    Plots the Poincaré section for the double pendulum.
    The section is defined by phi1 = 0 with d_phi1 > 0.
    We plot phi2 vs d_phi2 at these crossings.
    """
    phi1 = solution[:, 0]
    d_phi1 = solution[:, 1]
    phi2 = solution[:, 2]
    d_phi2 = solution[:, 3]

    # Find indices where phi1 crosses zero with positive velocity
    # Crossing from negative to positive: phi1[i] < 0 and phi1[i+1] > 0
    # Also check d_phi1 > 0 to ensure positive velocity direction
    # Note: d_phi1 is angular velocity, so checking d_phi1[i] > 0 is usually sufficient for direction,
    # but strictly speaking, the sign change of phi1 defines the geometric crossing.

    # Indices where phi1 changes sign
    sign_change = (phi1[:-1] * phi1[1:]) < 0

    # Indices where it goes from negative to positive
    neg_to_pos = (phi1[:-1] < 0) & (phi1[1:] > 0)

    # Filter by velocity condition (optional but good practice for Poincaré sections)
    # We want crossings where velocity is positive.
    valid_indices = np.where(neg_to_pos & (d_phi1[:-1] > 0))[0]

    poincare_phi2 = []
    poincare_d_phi2 = []

    for i in valid_indices:
        # Linear interpolation to find the exact time t_cross where phi1 is zero
        # phi1(t) approx = phi1[i] + slope * (t - t[i])
        # 0 = phi1[i] + (phi1[i+1] - phi1[i]) / (t[i+1] - t[i]) * (t_cross - t[i])

        # Fraction of the time step
        # 0 = y1 + (y2 - y1) * fraction
        # fraction = -y1 / (y2 - y1)
        frac = -phi1[i] / (phi1[i+1] - phi1[i])

        # Interpolate phi2 and d_phi2
        val_phi2 = phi2[i] + frac * (phi2[i+1] - phi2[i])
        val_d_phi2 = d_phi2[i] + frac * (d_phi2[i+1] - d_phi2[i])

        # Map phi2 to [-pi, pi]
        val_phi2 = (val_phi2 + np.pi) % (2 * np.pi) - np.pi

        poincare_phi2.append(val_phi2)
        poincare_d_phi2.append(val_d_phi2)

    # Plot
    plt.figure(figsize=(8, 8))
    plt.scatter(poincare_phi2, poincare_d_phi2, s=2, alpha=0.6, color='purple')
    plt.title('Poincaré Section (phi1=0, d_phi1>0)')
    plt.xlabel('phi2 (rad)')
    plt.ylabel('d_phi2 (rad/s)')
    plt.grid(True)
    plt.xlim(-np.pi, np.pi)
    plt.show()

"""**Reasoning**:
Update the simulation parameters (t_max = 100), run the simulation again, and call the newly defined `plot_poincare_section` function to visualize the results as requested.


"""

# Update simulation parameters
t_max = 100

# Solve the system again with the longer duration
t, solution = solve_double_pendulum(y0, t_max, omega0)

# Generate the Poincaré section plot
plot_poincare_section(t, solution)

"""## Final Task

### Subtask:
Verify the Poincaré section is generated correctly.

## Summary:

### Q&A
**Q: How was the Poincaré section constructed for the double pendulum system?**
A: The section was constructed by monitoring the trajectory of the first pendulum. Specifically, the analysis identified moments where the first angle $\phi_1$ crossed zero moving in a positive direction (transitioning from negative to positive with $\dot{\phi}_1 > 0$). At these specific timestamps, the state of the second pendulum ($\phi_2$ and $\dot{\phi}_2$) was recorded and plotted.

### Data Analysis Key Findings
- **Event Detection Logic:** The analysis successfully implemented logic to detect specific "crossing events" defined by the condition where $\phi_1 = 0$ and angular velocity $\dot{\phi}_1 > 0$.
- **Precision Interpolation:** To address the discrete nature of the time steps, linear interpolation was used to calculate the exact values of $\phi_2$ and $\dot{\phi}_2$ at the precise fractional time step where the crossing occurred, ensuring higher accuracy than simply taking the nearest data point.
- **Data Normalization:** The resulting angles for the second pendulum ($\phi_2$) were mathematically wrapped to the interval $[-\pi, \pi]$ to ensure the plot remained within a standard phase space domain.
- **Extended Simulation:** The simulation duration was increased to $t_{max} = 100$ seconds to generate a sufficient number of crossing events for the scatter plot to be meaningful.

### Insights or Next Steps
- **Chaos Diagnosis:** The pattern formed by the scattered points in the Poincaré section acts as a diagnostic tool; distinct closed loops indicate quasi-periodic behavior, while a "sea" of scattered points suggests the system is in a chaotic regime.
- **Increasing Density:** While 100 seconds provides an initial view, generating a high-fidelity Poincaré section typically requires a significantly longer simulation duration (e.g., $t > 1000s$) or aggregating runs from multiple initial conditions with the same total energy to fully reveal the phase space structure.
"""