# -*- coding: utf-8 -*-
"""Driven Damped Pendulum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vfc9DflMPw-XrAyktAqpoLHBD3OTvhki
"""



import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

def solve_driven_pendulum(phi_0, phi_dot_0, beta, omega_0, gamma, omega, t_max=50, dt=0.01):
    """
    Solves the driven damped pendulum equation of motion:
    phi'' + 2*beta*phi' + omega_0^2 * sin(phi) = gamma * omega_0^2 * cos(omega * t)

    Parameters:
    - phi_0, phi_dot_0: Initial conditions for angle and angular velocity
    - beta: Damping coefficient
    - omega_0: Natural frequency
    - gamma: Drive amplitude factor
    - omega: Driving frequency
    - t_max: Total time for simulation
    - dt: Time step
    """

    # Define the system of first-order ODEs
    def model(state, t, beta, omega_0, gamma, omega):
        phi, phi_dot = state

        # d(phi)/dt = phi_dot
        dphi_dt = phi_dot

        # d(phi_dot)/dt = gamma * omega_0^2 * cos(omega * t) - 2 * beta * phi_dot - omega_0^2 * sin(phi)
        dphi_dot_dt = (gamma * (omega_0**2) * np.cos(omega * t)) - (2 * beta * phi_dot) - ((omega_0**2) * np.sin(phi))

        return [dphi_dt, dphi_dot_dt]

    # Time array
    t = np.arange(0, t_max, dt)

    # Initial state vector
    y0 = [phi_0, phi_dot_0]

    # Solve ODE
    solution = odeint(model, y0, t, args=(beta, omega_0, gamma, omega))

    return t, solution

# Example Usage

# Parameters
phi_0 = 0.0          # Initial angle
phi_dot_0 = 0.0      # Initial angular velocity
omega = 2 * np.pi    # Driving frequency (Period T = 1, so omega = 2 * pi / T)
omega_0 = 1.5*omega        # Natural frequency
beta = omega_0/4           # Damping coefficient

gamma = 0.9          # Drive amplitude (try > 1 for chaotic behavior regions)

t_max =6

# Solve
t, sol = solve_driven_pendulum(phi_0, phi_dot_0, beta, omega_0, gamma, omega, t_max)

# Extract phi and phi_dot
phi = sol[:, 0]
phi_dot = sol[:, 1]

# Plotting
plt.figure(figsize=(12, 5))

# Plot Time Series
plt.subplot(1, 2, 1)
plt.plot(t, phi, label=r'$\phi(t)$')
plt.xlabel('Time (t)')
plt.ylabel(r'Angle ($\phi$)')
plt.title(r'Time Evolution of $\phi$') # Fixed: changed to a raw string
plt.grid(True, alpha=0.3)
plt.legend()

# Plot Phase Portrait
plt.subplot(1, 2, 2)
plt.plot(phi, phi_dot, lw=0.5)
plt.xlabel(r'$\phi$')
plt.ylabel(r'$\dot{\phi}$')
plt.title('Phase Portrait')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()